apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-devops-admin-rb
subjects:
- kind: Group
  name: ocid1.group.oc1..aqwertyjq5ekblsmp4wsdedqagfqknwa3ej5bmrvu6da
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: my-devops-admin
  apiGroup: rbac.authorization.k8s.io