apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-client
  namespace: infra-common
spec:
  containers:
    - name: zookeeper-client
      image: ranchercharts/confluentinc-cp-zookeeper:5.3.0
      command: ['sh', '-c', 'exec tail -f /dev/null']