apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-devops-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - get
  - list
  - watch  