{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      - "{{ .Values.ingress.domain }}"
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: "{{ .Values.ingress.domain }}"
      http:
        paths:
        - path: "{{ .Values.ingress.paths.path }}"
          backend:
            serviceName: "{{ template "fullname" . }}"
            servicePort: {{ .Values.service.externalPort }}
{{- end }}
