apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: logging
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - "*.api.com"
      secretName: my-managed-api-tls
  rules:
  - host: kibana-prod.api.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: 5601    
# spec:
#   rules:
#     - http:
#         paths:
#          - path: /*
#            backend:
#              serviceName: kibana
#              servicePort: 5601